baseURL = 'https://vishwas1.github.io/hackDID/'
languageCode = 'en-us'
title = 'Hypersign Hack DID'
theme = 'github-style'
defaultContentLanguage = 'en'
lastmod = true

[params]
  author = "Hypersign.id"
  description = "Own your identity and data"
  github = "hypersign-protocol"
  facebook = "hypersign-protocol"
  twitter = "hypersignchain"
  linkedin = "hypersign-protocol"
  instagram = "hypersign-protocol"
  tumblr = "hypersign-protocol"
  email = "connect@hypermine.in"
  url = "https://hypersign.id"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/github.png"
  location = "India"
  enableGitalk = true

[[params.links]]
    title = "Link"
    href = "https://github.com/hypersign-protocol"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

